---
docker:
  builds:
    - path: .
      dockerfile: Dockerfile
      docker_repo: balena/open-balena-base
    - path: .
      dockerfile: Dockerfile.no-systemd
      docker_repo: balena/open-balena-base:no-systemd
