#!/command/with-contenv bash
# shellcheck shell=bash

# Redirect all future stdout/stderr to s6-log
exec > >(exec s6-log p"confd[$$]:" 1 || true) 2>&1

exec /etc/s6-overlay/scripts/configure-balena.sh
