name: Flowzone

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches: [main, master]
  # allow external contributions to use secrets within trusted code
  pull_request_target:
    types: [opened, synchronize, closed]
    branches: [main, master]

jobs:
  flowzone:
    name: Flowzone
    uses: product-os/flowzone/.github/workflows/flowzone.yml@kyle/docker-test-multiarch
    secrets: inherit
    with:
      docker_images: |
        docker.io/balena/open-balena-base
      bake_targets: |
        default,
        no-systemd
